## Arithmetic and Linear Algebra with Arrays
### Diving Into NumPy
*Curtis Miller*

Let's begin the notebook with further demonstrations of arithmetic and broadcasting with NumPy arrays.

In [1]:
import numpy as np
from numpy.random import randn
import numpy.linalg as ln

arr1 = np.array(randn(3, 3, 3) * 10, dtype = np.int64)
arr2 = np.array(randn(3, 3, 3) * 10, dtype = np.int64)
print(arr1)

[[[ -7  -4   3]
  [ -7   6  20]
  [  3 -10  10]]

 [[ -9  11   5]
  [  9 -14   9]
  [  1 -10   3]]

 [[ 18   0  14]
  [ -3 -12  10]
  [  7   4   0]]]


In [2]:
print(arr2)

[[[  1   0   0]
  [  3  -1   3]
  [-15   5  -7]]

 [[-15  -8 -11]
  [ -6 -15  16]
  [ 19  14   4]]

 [[  7   3   2]
  [ -7   6   9]
  [  2  -6  -5]]]


In [3]:
print(arr1 + 100)

[[[ 93  96 103]
  [ 93 106 120]
  [103  90 110]]

 [[ 91 111 105]
  [109  86 109]
  [101  90 103]]

 [[118 100 114]
  [ 97  88 110]
  [107 104 100]]]


In [4]:
print(arr1 / 2)

[[[ -3.5  -2.    1.5]
  [ -3.5   3.   10. ]
  [  1.5  -5.    5. ]]

 [[ -4.5   5.5   2.5]
  [  4.5  -7.    4.5]
  [  0.5  -5.    1.5]]

 [[  9.    0.    7. ]
  [ -1.5  -6.    5. ]
  [  3.5   2.    0. ]]]


In [5]:
print(arr1 ** 2)

[[[ 49  16   9]
  [ 49  36 400]
  [  9 100 100]]

 [[ 81 121  25]
  [ 81 196  81]
  [  1 100   9]]

 [[324   0 196]
  [  9 144 100]
  [ 49  16   0]]]


In [6]:
print(arr1 * arr2)

[[[  -7    0    0]
  [ -21   -6   60]
  [ -45  -50  -70]]

 [[ 135  -88  -55]
  [ -54  210  144]
  [  19 -140   12]]

 [[ 126    0   28]
  [  21  -72   90]
  [  14  -24    0]]]


In [7]:
print(arr1 ** (arr2 / 4))    # Watch out for nan and inf!

[[[             nan   1.00000000e+00   1.00000000e+00]
  [             nan   6.38943104e-01   9.45741609e+00]
  [  1.62478273e-02              nan   1.77827941e-02]]

 [[             nan   8.26446281e-03   1.19627902e-02]
  [  3.70370370e-02              nan   6.56100000e+03]
  [  1.00000000e+00              nan   3.00000000e+00]]

 [[  1.57299334e+02   0.00000000e+00   3.74165739e+00]
  [             nan              nan   1.77827941e+02]
  [  2.64575131e+00   1.25000000e-01              inf]]]


C:\Users\prasadr\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in power
  """Entry point for launching an IPython kernel.
C:\Users\prasadr\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


Here I demonstrate broadcasting behavior.

In [8]:
arr3 = np.array([[[0, 1, 0]]])
print(arr3)

[[[0 1 0]]]


In [9]:
print(arr1 * arr3)

[[[  0  -4   0]
  [  0   6   0]
  [  0 -10   0]]

 [[  0  11   0]
  [  0 -14   0]
  [  0 -10   0]]

 [[  0   0   0]
  [  0 -12   0]
  [  0   4   0]]]


In [10]:
print(arr3.shape)

(1, 1, 3)


In [11]:
print(arr1 * arr3)

[[[  0  -4   0]
  [  0   6   0]
  [  0 -10   0]]

 [[  0  11   0]
  [  0 -14   0]
  [  0 -10   0]]

 [[  0   0   0]
  [  0 -12   0]
  [  0   4   0]]]


In [12]:
arr4 = arr3.transpose((0, 2, 1))
print(arr4)

[[[0]
  [1]
  [0]]]


In [13]:
print(arr1 * arr4)

[[[  0   0   0]
  [ -7   6  20]
  [  0   0   0]]

 [[  0   0   0]
  [  9 -14   9]
  [  0   0   0]]

 [[  0   0   0]
  [ -3 -12  10]
  [  0   0   0]]]


In [14]:
arr5 = arr3.transpose((2, 0, 1))
print(arr5)

[[[0]]

 [[1]]

 [[0]]]


In [15]:
print(arr1 * arr5)

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ -9  11   5]
  [  9 -14   9]
  [  1 -10   3]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [ ]:
print(arr1 > arr5)

In [17]:
arr4 = arr3.transpose((0 ,2, 1))
print(arr4)

[[[0]
  [1]
  [0]]]


A quick demo of `reshape`:

In [18]:
arr6 = np.arange(0, 8)
print(arr6)

[0 1 2 3 4 5 6 7]


In [19]:
print(arr6.reshape(2, 4))    # Notice 2 * 4 = 8

[[0 1 2 3]
 [4 5 6 7]]


In [20]:
print(arr6.reshape(2, 2, 2))    # 2 * 2 * 2 = 8

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In this notebook we will manipulate the `iris` data set containing measurements of iris flowers of different species. We load in the `iris` data set with the following code:

In [21]:
from sklearn.datasets import load_iris
# Load iris data set
iris = load_iris().data[:, :]
print(iris)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [22]:
print(iris.T)

[[ 5.1  4.9  4.7  4.6  5.   5.4  4.6  5.   4.4  4.9  5.4  4.8  4.8  4.3
   5.8  5.7  5.4  5.1  5.7  5.1  5.4  5.1  4.6  5.1  4.8  5.   5.   5.2
   5.2  4.7  4.8  5.4  5.2  5.5  4.9  5.   5.5  4.9  4.4  5.1  5.   4.5
   4.4  5.   5.1  4.8  5.1  4.6  5.3  5.   7.   6.4  6.9  5.5  6.5  5.7
   6.3  4.9  6.6  5.2  5.   5.9  6.   6.1  5.6  6.7  5.6  5.8  6.2  5.6
   5.9  6.1  6.3  6.1  6.4  6.6  6.8  6.7  6.   5.7  5.5  5.5  5.8  6.   5.4
   6.   6.7  6.3  5.6  5.5  5.5  6.1  5.8  5.   5.6  5.7  5.7  6.2  5.1
   5.7  6.3  5.8  7.1  6.3  6.5  7.6  4.9  7.3  6.7  7.2  6.5  6.4  6.8
   5.7  5.8  6.4  6.5  7.7  7.7  6.   6.9  5.6  7.7  6.3  6.7  7.2  6.2
   6.1  6.4  7.2  7.4  7.9  6.4  6.3  6.1  7.7  6.3  6.4  6.   6.9  6.7
   6.9  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9]
 [ 3.5  3.   3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  3.7  3.4  3.   3.   4.
   4.4  3.9  3.5  3.8  3.8  3.4  3.7  3.6  3.3  3.4  3.   3.4  3.5  3.4
   3.2  3.1  3.4  4.1  4.2  3.1  3.2  3.5  3.1  3.   3.4  3.5  2.3  3.2
   3.5 

In [23]:
iris_cp = iris.copy()
iris_cp

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [24]:
# The last column will be made its own
y = iris_cp[:, 3]
# The rest will be another data set
X = np.concatenate((np.ones(shape = (iris_cp.shape[0], 1)), iris_cp[:, 0:3]), axis = 1)
print(y)

[ 0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  0.2  0.2  0.1  0.1  0.2
  0.4  0.4  0.3  0.3  0.3  0.2  0.4  0.2  0.5  0.2  0.2  0.4  0.2  0.2  0.2
  0.2  0.4  0.1  0.2  0.1  0.2  0.2  0.1  0.2  0.2  0.3  0.3  0.2  0.6  0.4
  0.3  0.2  0.2  0.2  0.2  1.4  1.5  1.5  1.3  1.5  1.3  1.6  1.   1.3  1.4
  1.   1.5  1.   1.4  1.3  1.4  1.5  1.   1.5  1.1  1.8  1.3  1.5  1.2  1.3
  1.4  1.4  1.7  1.5  1.   1.1  1.   1.2  1.6  1.5  1.6  1.5  1.3  1.3  1.3
  1.2  1.4  1.2  1.   1.3  1.2  1.3  1.3  1.1  1.3  2.5  1.9  2.1  1.8  2.2
  2.1  1.7  1.8  1.8  2.5  2.   1.9  2.1  2.   2.4  2.3  1.8  2.2  2.3  1.5
  2.3  2.   2.   1.8  2.1  1.8  1.8  1.8  2.1  1.6  1.9  2.   2.2  1.5  1.4
  2.3  2.4  1.8  1.8  2.1  2.4  2.3  1.9  2.3  2.5  2.3  1.9  2.   2.3  1.8]


In [25]:
print(X)

[[ 1.   5.1  3.5  1.4]
 [ 1.   4.9  3.   1.4]
 [ 1.   4.7  3.2  1.3]
 [ 1.   4.6  3.1  1.5]
 [ 1.   5.   3.6  1.4]
 [ 1.   5.4  3.9  1.7]
 [ 1.   4.6  3.4  1.4]
 [ 1.   5.   3.4  1.5]
 [ 1.   4.4  2.9  1.4]
 [ 1.   4.9  3.1  1.5]
 [ 1.   5.4  3.7  1.5]
 [ 1.   4.8  3.4  1.6]
 [ 1.   4.8  3.   1.4]
 [ 1.   4.3  3.   1.1]
 [ 1.   5.8  4.   1.2]
 [ 1.   5.7  4.4  1.5]
 [ 1.   5.4  3.9  1.3]
 [ 1.   5.1  3.5  1.4]
 [ 1.   5.7  3.8  1.7]
 [ 1.   5.1  3.8  1.5]
 [ 1.   5.4  3.4  1.7]
 [ 1.   5.1  3.7  1.5]
 [ 1.   4.6  3.6  1. ]
 [ 1.   5.1  3.3  1.7]
 [ 1.   4.8  3.4  1.9]
 [ 1.   5.   3.   1.6]
 [ 1.   5.   3.4  1.6]
 [ 1.   5.2  3.5  1.5]
 [ 1.   5.2  3.4  1.4]
 [ 1.   4.7  3.2  1.6]
 [ 1.   4.8  3.1  1.6]
 [ 1.   5.4  3.4  1.5]
 [ 1.   5.2  4.1  1.5]
 [ 1.   5.5  4.2  1.4]
 [ 1.   4.9  3.1  1.5]
 [ 1.   5.   3.2  1.2]
 [ 1.   5.5  3.5  1.3]
 [ 1.   4.9  3.1  1.5]
 [ 1.   4.4  3.   1.3]
 [ 1.   5.1  3.4  1.5]
 [ 1.   5.   3.5  1.3]
 [ 1.   4.5  2.3  1.3]
 [ 1.   4.4  3.2  1.3]
 [ 1.   5. 

In [26]:
# Matrix product
X_sq = X.T.dot(X)
print(X_sq)

[[  150.     876.5    458.1    563.8 ]
 [  876.5   5223.85  2670.98  3484.25]
 [  458.1   2670.98  1427.05  1673.91]
 [  563.8   3484.25  1673.91  2583.  ]]


In [27]:
# Matrix inverse
X_sq_inv = ln.inv(X_sq)
print(X_sq_inv)

[[ 0.86171781 -0.13800334 -0.06693333  0.04144097]
 [-0.13800334  0.06129955 -0.03658066 -0.02885944]
 [-0.06693333 -0.03658066  0.06519657  0.02170344]
 [ 0.04144097 -0.02885944  0.02170344  0.01620576]]


In [28]:
beta = X_sq_inv.dot(X.T.dot(y))
print(beta)    # Coefficients of a linear model

[-0.24872359 -0.21027133  0.22877721  0.52608818]


With the above code, we estimated a linear model!

$\hat{\beta} = (X^T X)^{-1} X^T y$

This is the least-squares solution to the equation:

$y = X\beta$

In [29]:
# SVD decomposition of iris_cp
iris_svd = ln.svd(iris_cp)
print(iris_svd[1])    # Spectral values of iris_cp

[ 95.95066751  17.72295328   3.46929666   1.87891236]


In [30]:
# Left-singular vectors
print(iris_svd[0])

[[ -6.16171172e-02   1.29969428e-01  -5.58364155e-05 ...,  -9.34637342e-02
   -9.60224157e-02  -8.09922905e-02]
 [ -5.80722977e-02   1.11371452e-01   6.84386629e-02 ...,   3.66755322e-02
   -3.24463474e-02   1.27273399e-02]
 [ -5.67633852e-02   1.18294769e-01   2.31062793e-03 ...,   3.08252776e-02
    1.95234663e-01   1.35567696e-01]
 ..., 
 [ -9.40702260e-02  -4.98348018e-02  -4.14958083e-02 ...,   9.81822841e-01
   -2.17978813e-02  -8.85972146e-03]
 [ -9.48993908e-02  -5.62107520e-02  -2.12386574e-01 ...,  -2.14264126e-02
    9.42038920e-01  -2.96933496e-02]
 [ -8.84882764e-02  -5.16210172e-02  -9.51442925e-02 ...,  -8.52768485e-03
   -3.02139863e-02   9.73577349e-01]]


In [31]:
print(iris_svd[0].shape)

(150, 150)


In [32]:
# Right-signular vectors
print(iris_svd[2])

[[-0.75116805 -0.37978837 -0.51315094 -0.16787934]
 [ 0.28583096  0.54488976 -0.70889874 -0.34475845]
 [ 0.49942378 -0.67502499 -0.05471983 -0.54029889]
 [ 0.32345496 -0.32124324 -0.48077482  0.74902286]]


In [33]:
print(iris_svd[2].shape)

(4, 4)
